credentials:
  usernames:
    admin:
      email: a01571000@tec.mx
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: Luis López
      password: admin # Will be hashed automatically
    demo:
      email: a01383328@tec.mx
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: Azahel Ramírez
      password: VivaAerobus2024 # Will be hashed automatically

cookie:
  expiry_days: 30
  key: "0123456789" # Must be string
  name: streamlitlogin-cookie
# pre-authorized: # (Provides the list of emails of unregistered users who are authorized to register.)
#   emails:
#     - melsby@gmail.com
